name: tests

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Deno 
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.32.1"
      - name: Run Tests
        run: deno test

